language: node_js
node_js: "6"
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

install:
- npm install

script:
- if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi
