# Appveyor: for producing and deploying Windows builds
#------------------------------------------------------

# Test against this version of Node.js
environment:
  nodejs_version: "8"
  GITHUB_TOKEN:
    secure: fxs30i1bh6CeJPKr3/shIxXr73kd0RgEJh9VQ6zEVe7hoaRNVmSaAnj4V/MwbY+F

platform:
- x64

# fetch repository as zip archive
shallow_clone: true

branches:
  only:
  - master
  - /^v\d\.\d\.\d/

cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'

init:
- git config --global core.autocrlf input

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g npm@latest
- set PATH=%APPDATA%\npm;%PATH%
- npm install

test_script:
- node --version
- npm --version
- if %APPVEYOR_REPO_TAG% EQU false npm run make

build_script:
- IF %APPVEYOR_REPO_TAG% EQU true npm run publish

artifacts:
  - path: 'out/**/*.zip'
  - path: 'out/**/*.exe'
